version: '3.1'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: trade
      MYSQL_DATABASE: poketrade
    cap_add: [ SYS_NICE ]
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: trade
    ports:
      - "8080:80"
    depends_on:
      - "db"
